export default Images = [
    {url: require('../assets/flower2.jpg')},
    {url: require('../assets/pets.jpg')},
    {url: require('../assets/room1.jpg')},
    {url: require('../assets/room2.jpg')},
    {url: require('../assets/room3.jpg')},
    {url: require('../assets/room4.jpg')},
    {url: require('../assets/room5.jpg')},
    {url: require('../assets/room6.jpg')},
    {url: require('../assets/todo image.jpg')},
    {url: require('../assets/dog.jpg')},
    {url: require('../assets/background.jpg')},
    {url: require('../assets/flower.jpg')},
    {url: require('../assets/gitImage.jpg')},
    {url: require('../assets/todo.jpg')},
]